export const CREATE_COURSE = 'CREATE_COURSE';
export const LOAD_SERVICES_SUCCESS = 'LOAD_SERVICES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_AUTHORS_SUCCESS = 'CREATE_AUTHORS_SUCCESS';
export const UPDATE_AUTHORS_SUCCESS = 'UPDATE_AUTHORS_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
